### PR TITLE
Add machine readable license info

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@brillout it would be nice if you could dual license this under `CC0 or MIT`, because MIT is more widely accepted.

**Review by graingert — COMMENTED** [review]
Eek, that looks like CCO not CC0

**Comment by graingert** [comment]
Sorry!

**Comment by brillout** [comment]
CC0 is more permissive, so what's the advantage of adding a MIT license?
And wouldn't the MIT license render the CC0 license useless?

**Comment by brillout** [comment]
No probs, just create another PR

**Pull request merged**
